name: Auto Update

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
        - "fix_update"

jobs:
  CheckUpdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Auto Checking Update
        run: |
          python -m pip install requests
          python ./updateChecker.py

      - name: Commit & Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "auto update plugins"
          push_options: --force
          branch: main
