name: Auto Update

on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches: "fix_update_v2"

jobs:
  CheckUpdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          github_token: ${{ secrets.UPDATER }}
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Auto Checking Update
        run: |
          python -m pip install requests
          python ./updateChecker.py

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          message: auto checking update
          branch: main
          force: true
        
